export default {
    general: {
        light: "#FFF",
        dark: "#000",
        darkTransparent: "rgba(0,0,0,.5)",
        lightTransparent: "rgba(255,255,255,.4)",
        lightBlueTransparent: "rgba(173, 202, 208, .5)",
        background: "#C9F1EA",
        borders: "#D9D9D9",
        shadow: "#D9D9D9",
        accentBlue: "#DBF4F0",
    },
    input: {
        background: "",
        blueGrey: "#f8f8f8",
    },
    text: {
        dark: "#000",
        darkTransparent: "rgba(0,0,0,.5)",
        light: "#FFF",
    },
    navBar: {
        activeBackground: "#C9F1EA",
        bar: "#FFF",
        icons: "#000",
        activeIcon: "#000",
    },
    button: {
        light: "#FFF",
        dark: "#000",
        textLight: "#FFF",
        textDark: "#000",
        textCancel: "#B50F0F",
        lightBlue: "#C9F1EA",
        textDarkTransparent: "rgba(0,0,0,.5)",
        shadow: "#1e1e1e",
        grey: "#D9D9D9",
        green: "rgb(51, 185, 92)",
        greenAccent: "rgb(28, 126, 58)",
        greenTransparent: "rgba(51, 185, 92, .5)",
    },
    cardColors: {
        white: "#FFFFFF",
        black: "#000000",
        blue: "#0048BA",
        lightBlue: "#7CB9E8",
        pink: "#F19CBB",
        red: "#DB2D43",
        lightRed: "#CB4154",
        orange: "#C46210",
        yellow: "#FFEF00",
        lightYellow: "#FFFF99",
        green: "#006B3C",
        lime: "#D0FF14",
    }
}