export default {
    // blue: "rgb(56,182,255)",
    // light: "#FFF",
    // greyish: "#1e1e1e",
    // dark: "#000",
    // pink: "#F7EEFF",
    // lightblue: "#CCEAFF",
    // brightblue: "#72EEFF",
    // mintgreen: "#E4F3C2",
    // transparentDark: "rgba(0,0,0,.8)",
    general: {
        light: "#FFF",
        dark: "#000",
        darkTransparent: "rgba(0,0,0,.5)",
        lightBlueTransparent: "rgba(173, 202, 208, .5)",
        background: "#C9F1EA",
        borders: "#D9D9D9",
        shadow: "#D9D9D9",
        accentBlue: "#DBF4F0",
    },
    text: {
        dark: "#000",
        darkTransparent: "rgba(0,0,0,.5)",
        light: "#FFF",
    },
    navBar: {
        activeBackground: "#C9F1EA",
        bar: "#FFF",
        icons: "#000",
        activeIcon: "#000",
    },
    button: {
        light: "#FFF",
        dark: "#000",
        textLight: "#FFF",
        textDark: "#000",
        textCancel: "#B50F0F",
        lightBlue: "#C9F1EA",
        textDarkTransparent: "rgba(0,0,0,.5)",
        shadow: "#1e1e1e",
        grey: "#D9D9D9",
    },
}